[package]
name = "mutant"
version = "0.1.0"
authors = ["madprops"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.3"
rand = "0.7.3"
gif = "0.10.3"